#!/bin/sh
# $Id: op_stop,v 1.3 2000/11/14 00:46:30 moz Exp $ 

echo "Stopping profiling and killing daemon"
oprofctl --stop
 
# make sure the daemon is dead
PID=`ps x | grep oprofiled | grep -v grep | awk '{print $1}'`
if [ "$PID" != "" ]
then
	kill $PID
fi
