#!/bin/sh

# cpu MHz         : 350.808548   
CPU_MHZ=`cat /proc/cpuinfo | grep MHz | awk -F: '{print $2}'`
 
set -x 
TIME1=`./rdtsc`
time sh $1
TIME2=`./rdtsc`
set +x 

DIFF=`min $TIME1 $TIME2`
 
echo "$DIFF ticks "
DIFFM=`div $DIFF 1000000`
SECS=`div $DIFFM $CPU_MHZ`
echo "$SECS seconds"
