#!/bin/sh

# useful for dumping ...

echo "NOTE: op_dump is deprecated. Please use opcontrol --dump" >&2
 
if [ ! -d /proc/sys/dev/oprofile ]; then
	echo "You must have the oprofile module loaded to dump data." >&2
	exit 1
fi
 
if [ ! -w /proc/sys/dev/oprofile/dump ]; then
	echo "Cannot initiate dump." >&2
	exit 1
fi
 
echo 1 >/proc/sys/dev/oprofile/dump

exit 0
