#!/bin/sh
# $Id: op_stop,v 1.1 2002/05/06 18:00:35 movement Exp $ 
# COPYRIGHT (C) 2000 THE VICTORIA UNIVERSITY OF MANCHESTER and John Levon
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.
#

# FIXME: support different base dir ??
 
if test -f /var/lib/oprofile/lock; then
	echo "Stopping profiling and killing daemon"
	echo 1 >/proc/sys/dev/oprofile/dump_stop
fi

COUNT=0
while test `pidof oprofiled`
do
	sleep 1 
	 
	COUNT=`expr $COUNT + 1`
	if [ "$COUNT" -eq 30 ]; then
		echo "Daemon stuck shutting down; killing !"
		kill -9 `pidof oprofiled`
		rm -f /var/lib/oprofile/lock
		exit 0
	fi
done
 
# if profiler is not started consider as ok to try to stop it.
exit 0
